package com.example.firstproject.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_DASHBOARD = "dashboard"
const val ROUTE_ADMIN_DASHBOARD = "admin_dashboard"
const val ROUTE_SPLASH = "splash"
const val ROUTE_ADD_PRODUCT = "add_product"
const val ROUTE_EDIT_PRODUCT = "edit_product"
const val ROUTE_CONTACT_US = "contact_us"
const val ROUTE_LANDING = "landing"
const val ROUTE_SHOWCASE = "showcase"
const val ROUTE_WELCOME = "welcome"
const val ROUTE_LUX_STORY = "lux_story"
const val ROUTE_CAROUSEL = "carousel"
const val ROUTE_LUX_SALON_HOME = "lux_salon_home"
const val ROUTE_SERVICE_DETAIL = "service_detail"
const val ROUTE_SERVICES = "services"
const val ROUTE_ABOUT_US = "about_us"
